version: '3.4'

services:
  dockerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "80"
    ports:
      - "8000:80"

  dockermvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "80"
    ports:
      - "9000:80"

