version: '3.4'

services:
  dockerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dockermvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

